### ISSUE TITLE
milliseconds too long, maybe better to use word abbreviation?

### ISSUE THREAD

**Issue by whoizit** [noojee/dcli#163]
I propose for the scripts to abbreviate:

milliseconds -> ms
seconds -> s
minutes -> m
hours -> h

or

milliseconds -> msec
seconds -> sec
minutes -> min
hours -> hour

**Comment by bsutton** [comment]
The choice of names was based on using the same names as the Duration class.
The idea being that this would make it easier for users to remember/learn.
Abbreviations are also generally frowned upon and with auto-complete they
don't add much advantage.


S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by whoizit** [comment]
ok, thanks
