### ISSUE TITLE
How to read  none color ascii outputs from other applications?

### ISSUE THREAD

**Issue by Hu-Wentao** [noojee/dcli#165]
I use `forEach` method to call other app, it very useful, Thank you for your great work!
but, other app outputs some colorful String, I can not treating them with regex, Can you provide some features or other suggestions?

**Comment by bsutton** [comment]
Can you provide some more details as I'm not certain of what you are asking?

If the app is outputting ansi escape characters you can strip them using:
```dart
var strippedString = Ansi.strip(stringWithAnsiEscapes);
```

**Comment by Hu-Wentao** [comment]
Ohhh, thank you very much, It worked !
This saves me a lot of time!
