### ISSUE TITLE
dcli warmup description mistake or logical error

### ISSUE THREAD

**Issue by whoizit** [noojee/dcli#172]
**Describe the bug**
warmup description says 'Runs pub upgrade on the given directory.' but it's don't do `pub upgrade` it's do `pub get`. 
it drove me crazy and I had to go into the code to figure it out.

I think `warmup` means work like `pub upgrade`, not like `pub get`

**Comment by bsutton** [comment]
I think it should actually do a pub get.

The problem with pub upgrade it can make you app unstable by changing the dep versions all of the time.

I'm inclined to just update the warm doco to reflect that it runs pub get.

thoughts?

**Comment by whoizit** [comment]
you are an native English speaker, you are the author, you know best

**Comment by whoizit** [comment]
> The problem with pub upgrade it can make you app unstable by changing the dep versions all of the time.
I agree

**Comment by whoizit** [comment]
It might be better just to remove `warmup` from the dcli or rename it to `dcli get`

**Comment by whoizit** [comment]
also `dcli upgrade` can be renamed to `dcli self-upgrade`

**Comment by whoizit** [comment]
I mean to avoid different names for subcommands in `dcli` and `pub`
