### ISSUE TITLE
Can there be a `CONTRIBUTING.md` added to the project?

### ISSUE THREAD

**Issue by Luckey-Elijah** [noojee/dcli#180]
A clear guide to how myself and future developers can contribute to the `dcli` project (via PR's or issues).

Some items to include:
- clone the sibling repo(s)
- how to generate `*.g.dart` files

Thank! I really enjoy the package.

**Comment by bsutton** [comment]
Thanks for the interest, I'm glad you are also enjoying dcli.
I've added a contributing.md file.
The .g files are currently just experiments for the dcli pack command and serve no useful purpose.
They are generated by the dcli pack command.
I'm about to change how templates work so the use the dcli pack command and which point I will update the doco.
I'm also about to change to a multi-project repo by bringing dcli_core into the dcli repo as I think this will make it easier for contributors.

If you need any help getting started drop a comment on an issue or start a discussion thread.

**Comment by Luckey-Elijah** [comment]
Perfect! Thank you!
