### ISSUE TITLE
Getting the path of the dcli script 

### ISSUE THREAD

**Issue by cedvdb** [noojee/dcli#186]
I would like to be able to run this package https://pub.dev/packages/flutter_launcher_icons#book-guide from a dcli script.

The command provided with this package lets you parametrize the path of the configuration file like so:

```
flutter pub run flutter_launcher_icons:main -f <your config file name here>
```

The issue I have is that I'd like to have a premade configuration file provided by the script but it is a bit unclear how to get the path of said configuration file. I'm unsure how to get that path, especially since the script could be run directly eg: `my_cli` or via pub `dart run my_cli`.  So using `which` does not seem to be an option.

Here is an example folder structure:

```
  - bin
     my_cli.dart
  - configs
     launcher_icons_config.yaml
```

Is there a way to get that configuration file path ?

**Comment by bsutton** [comment]
join(DartProject.self.projectRoot, 'configs)

**Comment by cedvdb** [comment]
It seems that `pathToProjectRoot` gives the project I've installed the cli app into. However I can find another way to resolve this.

**Comment by bsutton** [comment]
The path to the script is

DartScript.self.pathTo???

**Comment by cedvdb** [comment]
I'm not sure if this is a question or a rhetorical one but:

Of all the commands available, none provide what I'm after, that is I tried:

```
  print(DartScript.self.pathToExe);
  print(DartScript.self.pathToInstalledExe);
  print(DartProject.self.pathToBinDir);
  print(DartProject.self.pathToDartToolDir);
  print(DartProject.self.pathToProjectRoot);
  print(DartProject.self.pathToTestDir);
  print(DartProject.self.pathToToolDir);
```

That being said, I do not need that anymore but it could be a feature that could be added in the library (or maybe not, you be the judge).

**Comment by bsutton** [comment]
So I'm a little unclear on what your structure is.

If you intend running the my_cli tool from the my_cli package directory then the DartProject idea should work as it will return the root of the my_cli package.

> What I was after was the path of the dependency

So my_cli being used in a separate package.

It sounds like there are three things.
flutter_launcher_icons:main
the my_cli tool
some package you want to run my_cli on: some_package

If thats the case you should complie my_cli

dcli compile --install my_cli

cd some_package
// run the my_cli command
my_cli  

The my_cli command can then use 'pwd' (a dcli global function) to obtain the directory you are working in or better
DartProject.fromPath(pathTo: pwd).pathToProjectRoot

This will give you the root of the some_package project provided your current directory is somewhere in that package.

**Comment by cedvdb** [comment]
I'm wasting both of us time here, first because I failed to express clearly what I was after secondly because I found a better alternative which does not require me to find that path. Therefor I'm closing this.
