### ISSUE TITLE
[Proposal] add multi pick menu

### ISSUE THREAD

**Issue by cedvdb** [noojee/dcli#187]
This is a proposal for a multi pick menu. The firebase cli does it well, where you can use arrow keys and space to pick your options and enter to pick one.

I took a look at the `menu` implementation but it is still a bit unclear to me how to:

  - listen to arrow key presses
  - rerender the option list when such a key is pressed.
  
  related: https://github.com/noojee/dcli/issues/161

**Comment by bsutton** [comment]
Dcli includes the dart_console package that support handling key presses.

**Comment by bsutton** [comment]
The cli_menu package might have what you want:

file:///home/bsutton/.pub-cache/hosted/pub.dartlang.org/cli_menu-0.3.0-nullsafety.0/lib/

**Comment by cedvdb** [comment]
cli_menu is not a multiselect but this one seems to have one:

https://pub.dev/packages/interact

which has a wide range of good looking command line "menus"
