### ISSUE TITLE
Unable to pick choice via `firebase init`

### ISSUE THREAD

**Issue by cedvdb** [noojee/dcli#188]
when

```dart
    run(
      'firebase init',
      runInShell: true,
    );
```

The cli does not display the menus, making it impossible to go forward. To reproduce this you need the [firebase-cli installed](https://firebase.google.com/docs/cli) and just run the above code.

maybe related to https://github.com/noojee/dcli/issues/187

**Comment by bsutton** [comment]
Why did you using runInShell?

Try start
https://pub.dev/documentation/dcli/latest/dcli/start.html


with the terminal = true option.

**Comment by cedvdb** [comment]
`runInShell` was used because without it the `firebase` command was said to not be in the path. I figured that maybe there was a restriction on using path executables without runInShell, ence why I used it. It correctly launch firebase with it but I'm not sure my reasoning is correct.

Here is are pictures of the different outputs I get depending if I run the command from git bash or from dcli:

![image](https://user-images.githubusercontent.com/22280985/153750907-59ce9bcb-f5f2-499d-bd1f-1bcdc8d4ac9d.png)
 
 Here with dcli run (or start):
 
![image](https://user-images.githubusercontent.com/22280985/153751030-21f25ae5-53d8-4e47-82e9-b21a13568458.png)

As you can see, there is no "Are you ready to proceed ?" on the one ran via dcli.
It seems like that read line by firebase is messing up the piping.

**Comment by cedvdb** [comment]
FYI why it works with runInShell is maybe bug on windows https://github.com/dart-lang/sdk/issues/38974

**Comment by cedvdb** [comment]
Running firebase is not the issue. I provided pictures to be more precise in a comment above. 

Anyway, since it works fine with :     `mode: ProcessStartMode.inheritStdio`, I'll stick to that.

**Comment by bsutton** [comment]
that is what the terminal option does in the start command.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100
