### ISSUE TITLE
`PackedResource` not exported in v1.16

### ISSUE THREAD

**Issue by AndreasMaros** [noojee/dcli#190]
The latest version of dcli apparently does not export the class `PackedResource`, which leads to a failure when trying to compile a library importing a `ResourceRegistry`:

```
lib/src/dcli/resource/generated/A09ecbce37fa7deef2b7c0153ac167b9d.g.dart:12:49: Error: Type 'PackedResource' not found.
class A09ecbce37fa7deef2b7c0153ac167b9d extends PackedResource {
                                                ^^^^^^^^^^^^^^
lib/src/dcli/resource/generated/resource_registry.g.dart:23:37: Error: 'PackedResource' isn't a type.
  static const resources = <String, PackedResource>{
                                    ^^^^^^^^^^^^^^
Error: AOT compilation failed
Generating AOT kernel dill failed!
```

**To Reproduce**
 - install dcli@1.16.2
 - put a file in `<project_root>/resource`
 - run `dcli pack`
 - import the registry from somewhere in the project (`ìmport '../lib/src/dcli/resource/generated/resource_registry.g.dart';`)
 - compile the project (`dcli compile src/main.dart` or `dart compile -o dist/exe src/main.dart`)

**Expected behavior**
The compilation succeeds and the packed resource can be extracted. This is what happens in v1.15.5.

---

On a less matter-of-fact note: Thanks for the great package!

**Comment by bsutton** [comment]
Can you check the beta.
I thought I had exposed it in 1.16 but its certainly in the beta.
If you can confirm the beta includes the export I will push it as a release.

**Comment by AndreasMaros** [comment]
Thanks for the quick reply! I can confirm the issue does not exist using [1.16.3-beta.1](https://pub.dev/packages/dcli/versions#prerelease).

**Comment by bsutton** [comment]
Andreas,

I'm just wondering if I can ask a favour.

I'm starting a new company that is going to offer a private repository service for dart.In the next month or so we are going to be looking for beta testers and I was wondering if you might be interested.
I was also hoping you might give some feedback on the draft for the brochure site (attached).
I will organise a free 12 subscription for you and a friend (regardless of feedback) if you flick me your email.

[OnePub.dev Website – home 03.pdf](https://github.com/noojee/dcli/files/8329718/OnePub.dev.Website.home.03.pdf)
